In [19]:
# dictionary
me = {'height': 182}

print(me['height'])

me['weight'] = 70

print(me)

180
{'height': 180, 'weight': 70}


In [21]:
# class
class Man:
  def __init__(self, name):
    self.name = name
    print("Initialized!")

  def hello(self):
    print("hello " + self.name + "!")

  def goodbye(self):
    print("Good-bye " + self.name + "!")

m = Man("Jeiyoon")
m.hello()
m.goodbye()

Initialized!
hello Jeiyoon!
Good-bye Jeiyoon!


In [28]:
# numpy
import numpy as np

x = np.array([1.0, 2.0, 3.0])
y = np.array([2.0, 4.0, 6.0])

# element-wise product
print(x * y)

A = np.array([[1, 2], 
              [3, 4]])
B = np.array([[3, 0], 
              [0, 6]])
# element-wsie product
print(A * B)

# broadcast
A = np.array([[1, 2], [3, 4]])
B = np.array([10, 20])
print(A * B)

# flatten
X = np.array([[51, 55], [14, 19], [0, 4]])
print(X)
X = X.flatten()
print(X)

[ 2.  8. 18.]
[[ 3  0]
 [ 0 24]]
[[10 40]
 [30 80]]
[[51 55]
 [14 19]
 [ 0  4]]
[51 55 14 19  0  4]
