In [8]:
# array
import numpy as np

A = np.array([1, 2, 3, 4])
print(A)

print(np.ndim(A))
print(A.shape)
print(A.shape[0])

B = np.array([[1, 2], 
              [3, 4],
              [5, 6]])
print(B)
print(np.ndim(B))
print(B.shape)

[1 2 3 4]
1
(4,)
4
[[1 2]
 [3 4]
 [5 6]]
2
(3, 2)


In [12]:
# matmul
A = np.array([[1, 2],
              [3, 4]])
print(A.shape)
B = np.array([[5, 6],
              [7, 8]])
print(B.shape)

print(A * B) # element-wise produce
print(np.dot(A, B)) # matmul

(2, 2)
(2, 2)
[[ 5 12]
 [21 32]]
[[19 22]
 [43 50]]


In [15]:
import numpy as np

X = np.array([1, 2])
print(X.shape) # 1 x 2

W = np.array([[1, 3, 5],
              [2, 4, 6]])
print(W.shape)

Y = np.dot(X, W)
print(Y)
print(Y.shape) # 1 x 3

(2,)
(2, 3)
[ 5 11 17]
(3,)


In [29]:
# three-layered neural net
# A = XW + B
import numpy as np

def sigmoid(z):
  return 1 / 1 + np.exp(-z)

def identitiy_function(y):
  return y

# input
X = np.array([1.0, 0.5])

# 1st layer
W1 = np.array([[0.1, 0.3, 0.5],
               [0.2, 0.4, 0.6]])

B1 = np.array([0.1, 0.2, 0.3])

print(W1.shape)
print(X.shape)
print(B1.shape)

A1 = np.dot(X, W1) + B1
print(A1) # [a1, a2, a3] / hidden
Z1 = sigmoid(A1)
print(Z1)

# 2nd layer
W2 = np.array([[0.1, 0.4],
               [0.2, 0.5],
               [0.3, 0.6]])
B2 = np.array([0.1, 0.2])

print(Z1.shape)
print(W2.shape)
print(B2.shape)

A2 = np.dot(Z1, W2) + B2
Z2 = sigmoid(A2)

# 3rd layer
W3 = np.array([[0.1, 0.3],
               [0.2, 0.4]])
B3 = np.array([0.1, 0.2])
A3 = np.dot(Z2, W3) + B3
print(A3)
Y = identitiy_function(A3)

print(Y)

(2, 3)
(2,)
(3,)
[0.3 0.7 1.1]
[1.74081822 1.4965853  1.33287108]
(3,)
(3, 2)
(2,)
[0.45514155 1.04806802]
[0.45514155 1.04806802]


In [31]:
# mlp
import numpy as np

def sigmoid(z):
  return 1 / 1 + np.exp(-z)

def init_network():
  network = {}
  network['W1'] = np.array([[0.1, 0.3, 0.5], [0.2, 0.4, 0.6]])
  network['b1'] = np.array([0.1, 0.2, 0.3])
  network['W2'] = np.array([[0.1, 0.4], [0.2, 0.5], [0.3, 0.6]])
  network['b2'] = np.array([0.1, 0.2])
  network['W3'] = np.array([[0.1, 0.3], [0.2, 0.4]])
  network['b3'] = np.array([0.1, 0.2])

  return network
  
def forward(network, x):
  W1, W2, W3 = network['W1'], network['W2'], network['W3']
  b1, b2, b3 = network['b1'], network['b2'], network['b3']

  a1 = np.dot(x, W1) + b1
  z1 = sigmoid(a1)
  
  a2 = np.dot(z1, W2) + b2
  z2 = sigmoid(a2)

  a3 = np.dot(z2, W3) + b3
  y = a3

  return y 
  
network = init_network()
x = np.array([1.0, 0.5])
y = forward(network, x)
print(y)

[0.45514155 1.04806802]
