In [5]:
# softmax
import numpy as np

a = np.array([0.3, 2.9, 4.0])

exp_a = np.exp(a)
print(exp_a)

sum_exp_a = np.sum(exp_a)
print(sum_exp_a)

y = exp_a / sum_exp_a
print(y)
print(np.sum(y))

[ 1.34985881 18.17414537 54.59815003]
74.1221542101633
[0.01821127 0.24519181 0.73659691]
1.0


In [7]:
# softmax
import numpy as np

def softmax(a):
  exp_a = np.exp(a)
  sum_exp_a = np.sum(exp_a)
  y = exp_a / sum_exp_a

  return y

a = np.array([0.3, 2.9, 4.0])
print(softmax(a)) 

[0.01821127 0.24519181 0.73659691]


In [14]:
# softmax with overflow
import numpy as np

a = np.array([1010, 1000, 990])
print(np.exp(a) / np.sum(np.exp(a)))

c = np.max(a)
print(c)

print(a - c)

print(np.exp(a-c) / np.sum(np.exp(a - c)))

print(np.sum(np.exp(a-c) / np.sum(np.exp(a - c))))

[nan nan nan]
1010
[  0 -10 -20]
[9.99954600e-01 4.53978686e-05 2.06106005e-09]
1.0


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:5: RuntimeWarning: overflow encountered in exp
  """
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:5: RuntimeWarning: invalid value encountered in true_divide
  """


In [18]:
# softmax
import numpy as np

def softmax(a):
  c = np.max(a)
  exp_a = np.exp(a - c)
  sum_exp_a = np.sum(exp_a)
  y = exp_a / sum_exp_a

  return y

a = np.array([1010, 1000, 990]) # (Note) 각각의 요소값은 큰 차이가 안나는데 exp라서 소맥 때리면 값차이 굉장히 큼 -> softmax에 exp 쓰는 이유
print(softmax(a))

[9.99954600e-01 4.53978686e-05 2.06106005e-09]
